[package]
name = "sim"
version = "0.1.0"
edition = "2021"

[lib]
name = "sim"
path = "src/lib.rs"

[[bin]]
name = "sim"
path = "src/main.rs"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
config = "0.15.6"
prettytable-rs = "0.10"